blank_issues_enabled: false
contact_links:
  - name: Minecolonies Bug Tracker
    about: Please follow the given template
    url: https://github.com/ldtteam/minecolonies/issues/new/choose
  - name: Structurize Bug Tracker
    about: Please follow the given template
    url: https://github.com/ldtteam/structurize/issues/new/choose
